services:

  nginx:
    image: nginx:latest
    container_name: sources_nginx
    ports:
      - "8080:8080"
      - "4443:4443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/:/usr/share/nginx/html
      - ./nginx/certs/:/etc/nginx/ssl:ro  # Read-only in container
    networks:
      - app_network
    links:
      - "app"
    depends_on:
      - app
      
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 0.0.0.0:3000:3000
    working_dir: /app
    networks:
      - app_network
    volumes:
      - .:/app
      - ./data/live:/data/live

networks:
  app_network:
    driver: bridge