services:
  nginx:
    image: nginx:latest
    container_name: sources_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/:/usr/share/nginx/html
    depends_on:
      - app
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 0.0.0.0:3000:3000
    working_dir: /app
    volumes:
      - .:/app
      - ./data/live:/data/live
