services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 0.0.0.0:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - ./data/live:/data/live





