

CREATE TABLE IF NOT EXISTS Event (
	"Uuid" INTEGER PRIMARY KEY,
	"Table" TEXT DEFAULT "Event" NOT NULL, 
	"Type" TEXT DEFAULT "" NOT NULL, 
	"Title" TEXT DEFAULT "" NOT NULL,
	"TimeCreated" INTEGER NOT NULL, 
	"TimeLastChange" INTEGER NOT NULL,
	
	"StartTime" INTEGER NOT NULL,
	"EndTime" INTEGER NOT NULL,
	"EventDate" TEXT NOT NULL

);

