
CREATE TABLE IF NOT EXISTS Project (
	"Uuid" INTEGER PRIMARY KEY,
	"Table" TEXT DEFAULT "Project" NOT NULL, 
	"Type" TEXT DEFAULT "" NOT NULL, 
	"Title" TEXT DEFAULT "" NOT NULL,
	"TimeCreated" INTEGER NOT NULL, 
	"TimeLastChange" INTEGER NOT NULL,
	
	"Goal" TEXT NOT NULL

);

